import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import RecoilProvider from '@/providers/recoil-provider'
import RootDialog from '@/dialogs/root-dialog'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilProvider>
          {children}
          <RootDialog />
        </RecoilProvider>
      </body>
    </html>
  )
}
